name: databricks-cicd
on:
    push:
      branches: ["fea*"]
    pull_request:
        branches: ["main", "dev"]

jobs:
  main:
    runs-on: ubuntu-latest
    # Name of the environment you created
    environment: databricks
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      # Install databricks CLI as per https://docs.databricks.com/dev-tools/cli/databricks-cli.html
      - name: Install databricks CLI
        run: |
         curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
  
      # List the databricks repos within the workspace whose credentials
      # are stored in the Github Environment "my-environment"
      - name: List databricks repos
        env:
          # Note the host is an "environment variable" in the Github Environment
          # while the token is a "secret" in the Github Environment
          DATABRICKS_HOST: ${{ vars.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: |
          databricks repos list
      - name: Get Branch Name
        id: branch_name
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
              branch_name="${{ github.event.pull_request.base.ref }}"
          elif [ "${{ github.event_name }}" == "push" ]; then
              branch_name="${{ github.ref_name }}"
          else
              echo "Unknown event type: ${{ github.event_name }}"
              exit 1
  
          fi

          echo "branch_name=$branch_name" >> $GITHUB_OUTPUT
          echo "!!!!!Lowercase branch name working!!!!!!!!!!!!!: $branch_name"

      - name: Update Branch at Workspace
        env:
          DATABRICKS_HOST: ${{ vars.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          
        run: |
          databricks repos update /Repos/cesar.higuita@dataknow.co/databricksdemo1 --branch ${{ steps.branch_name.outputs.branch_name }}

          echo "The branch: ${{ steps.branch_name.outputs.branch_name }} was updated sucessfully"

      - name: Run databricks job "TrainingModel"
        env:
          DATABRICKS_HOST: ${{ vars.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          JOB_NAME: 'TrainingModel'
          WAIT_TIMEOUT: '20m0s'
        run: |
          JOB_ID=$(databricks jobs list | grep -w $JOB_NAME | awk -F ' ' '{print $1}')
          databricks jobs run-now $JOB_ID --timeout $WAIT_TIMEOUT
          
          

      

        
